manifests/common/config/connector/rabbitmq.pp, manifests/server/config/connector/activemq.pp, manifests/server/config/connector/rabbitmq.pp
Continuation of https://github.com/puppetlabs/puppetlabs-mcollective/commit/e750b674f7f033e218c8879b2f556aa4bc358d89
=> (MODULES-773) Use string for host_iteration titles in future parser

Rakefile
it has to be a /regex/ rather than a "string"
=> fix grep in Rakefile

CHANGELOG.md
* fix rake task for releasing
* enable build on push on travis (we should document this step)
=> prep 2.1.1

manifests/init.pp, manifests/server/config/factsource/yaml.pp, spec/classes/mcollective_spec.rb
Cleaned up replacement for #174.
=> yaml cronjob: change before / require of file refresh-mcollective-metadata

.gitignore, manifests/init.pp, manifests/server/config/securityprovider/ssl.pp, spec/classes/mcollective_spec.rb
=> Fix ssl settings

.fixtures.yml, README.md, manifests/common/config/connector/activemq/hosts_iteration.pp, manifests/common/config/connector/rabbitmq/hosts_iteration.pp, manifests/init.pp, manifests/server/config.pp, manifests/server/config/connector/activemq/hosts_iteration.pp, manifests/server/config/connector/rabbitmq/hosts_iteration.pp, manifests/server/config/securityprovider/ssl.pp, metadata.json, spec/classes/mcollective_spec.rb
Rebased https://github.com/puppet-community/puppet-mcollective/pull/181 and then added a commit to fix stdlib 'pick' function issue and update tests.
=> Middleware ssl parameters rebase

manifests/defaults.pp, manifests/plugin.pp
For readability reasons, all if statements should be formatted the same way:
* Opening curly brace on the same line as the condition
* Closing curly brace on a new line following the last statement of the if / elsif / else block
* elsif and else keywords on the same line as the previous closing curly brace
=> Moves `if...else` onto separate lines

manifests/defaults.pp
Fixes missed bracket from #268
=> Fixes bracket to same line as else

manifests/init.pp, manifests/server/config/factsource/yaml.pp, spec/classes/mcollective_spec.rb
Superceeds https://github.com/puppet-community/puppet-mcollective/pull/199
Clean up specs, commits and the like
=> Improve Cron refresh

Gemfile, manifests/common/config/connector/activemq/hosts_iteration.pp, manifests/common/setting.pp
This is a rebase+split for PR #173.
**Updates:**
1. The fixes for MODULES-1253 & MODULES-1255 are no longer relevant as the code is significantly different now.
2.  The fix for MODULES-1252 is better solved in PR #205, but included here for completeness.
3.  The fix for MODULES-1250 is fixed here and should supersede, PR #87, #97, & #98.
Due to time constraints, I'm unable to invest time in learning how to write tests for this PR.
=> Fixing PR #173

manifests/server/config/factsource/yaml.pp
=> Added argument to tell factor to load puppet facts as well (Issue #262).

.rubocop.yml, .travis.yml, CONTRIBUTING.md, Gemfile, spec/spec_helper.rb
=> Update based on voxpupuli/modulesync_config

spec/classes/mcollective_spec.rb
* Instead of checking exact value of random given values, just check they're not default
=> Simplify splay tests

manifests/init.pp, manifests/server/config/connector/activemq/hosts_iteration.pp, manifests/server/config/connector/rabbitmq/hosts_iteration.pp, manifests/user.pp, manifests/user/connector.pp, spec/defines/mcollective__user_spec.rb
=> Enabled SSL Ciphers configuration

manifests/user.pp, spec/defines/mcollective__user_spec.rb
"or they won't be updated on cert changes"
Rebase of #226 with tests! 👍
=> User ssl files need to have an ensure parameter

manifests/server/config/securityprovider/ssl.pp
Here is a fix for ssl configuration with proper variable scopes
=> Fix puppet>=4 path handling

.gitignore, .msync.yml, .rubocop.yml, Gemfile, spec/acceptance/nodesets/docker/centos-5.yml, spec/acceptance/nodesets/docker/centos-6.yml, spec/acceptance/nodesets/docker/centos-7.yml, spec/acceptance/nodesets/docker/debian-7.yml, spec/acceptance/nodesets/docker/debian-8.yml, spec/acceptance/nodesets/docker/ubuntu-12.04.yml, spec/acceptance/nodesets/docker/ubuntu-14.04.yml, spec/acceptance/nodesets/docker/ubuntu-16.04.yml, spec/classes/mcollective_spec.rb, spec/defines/mcollective__actionpolicy__rule_spec.rb, spec/defines/mcollective__actionpolicy_spec.rb, spec/defines/mcollective__client__setting_spec.rb, spec/defines/mcollective__common__setting_spec.rb, spec/defines/mcollective__plugin_spec.rb, spec/defines/mcollective__server__setting_spec.rb, spec/defines/mcollective__setting_spec.rb, spec/defines/mcollective__user__setting_spec.rb, spec/defines/mcollective__user_spec.rb, spec/spec_helper.rb, spec/system/end_to_end_spec.rb
=> modulesync 0.15.0

.msync.yml, .rubocop.yml, .travis.yml, CHANGELOG.md, metadata.json, spec/spec_helper.rb
=> Modulesync 0.16.11 & Release 2.5.0

.github/CONTRIBUTING.md, .msync.yml, .overcommit.yml, .rubocop.yml, .travis.yml, Gemfile, spec/classes/mcollective_spec.rb, spec/defines/mcollective__actionpolicy__rule_spec.rb, spec/defines/mcollective__actionpolicy_spec.rb, spec/defines/mcollective__client__setting_spec.rb, spec/defines/mcollective__common__setting_spec.rb, spec/defines/mcollective__plugin_spec.rb, spec/defines/mcollective__server__setting_spec.rb, spec/defines/mcollective__setting_spec.rb, spec/defines/mcollective__user__setting_spec.rb, spec/defines/mcollective__user_spec.rb
=> Modulesync 0.21.0

.fixtures.yml, .gitignore, .msync.yml, .rspec_parallel, .rubocop.yml, Gemfile, metadata.json, spec/acceptance/nodesets/archlinux-2-x64.yml, spec/acceptance/nodesets/docker/ubuntu-16.04.yml
=> Modulesync 0.21.3

.msync.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile, lib/puppet/parser/functions/mco_array_to_string.rb, spec/acceptance/nodesets/docker/ubuntu-14.04.yml, spec/acceptance/nodesets/docker/ubuntu-16.04.yml, spec/classes/mcollective_spec.rb
=> modulesync 1.1.0

README.md
This got requested during the approval request in https://tickets.puppetlabs.com/browse/MODULES-6023
=> reorder param docs to the Reference section

.fixtures.yml, .github/CONTRIBUTING.md, .msync.yml, .travis.yml, Gemfile, spec/classes/coverage_spec.rb, spec/default_facts.yml, spec/spec_helper.rb
=> modulesync 2.2.0
