voxpupuli/puppet-mcollective

- manifests/common/config/connector/rabbitmq/hosts_iteration.pp
Currently the ssl.fallback variable always defaults to 0 for rabbitmq regardless of it's setting. This patch propagates the truthiness correctly to the respective config setting.
> fix propagation of middleware_ssl_fallback for rabbitmq

- CHANGELOG.md
- Rakefile
* move CHANGELOG to markdown format.
* add changes from this release
* adapt rakefile to check for the format we've had in CHANGELOG so far
(Release 2.1.0, rather than Releasing 2.1.0)
> prepare 2.1.0 release

- manifests/server/config/factsource/yaml.pp
- spec/classes/mcollective_spec.rb
In MCollective 2.8 the packages no longer put files into core_libdir
(MCO-583, MCO-315), which makes these file resources fail as the
parent directory is never created but is assumed to be created by
the package install.
`refresh-mcollective-metadata` should never have been put into
core_libdir to begin with as that's intended to be space owned by
native OS packages.   It's doubly inappropriate as it's not a
loadable ruby file for an MCollective extension, it's a helper
executable for this module.
Here we just put it in $site_libdir, as that is a directory that
this module creates and populates.
> Don't attempt to drop files in non-existent paths

- manifests/server/config/factsource/yaml.pp
See https://github.com/puppet-community/puppet-mcollective/issues/213 - the cronjob just often spams without any meaning because interfaces may appear and disappear at will on many systems and facter is not smart enough about it:
https://projects.puppetlabs.com/issues/15035
https://projects.puppetlabs.com/issues/15798
> fix issue #213 by silencing refresh-mcollective-metadata cronjob

- manifests/server/config/factsource/yaml.pp
- templates/refresh-mcollective-metadata.erb
Crontab environment variables are global and we do not as a matter of
best practice want to leak environment variables into other cron jobs.
We still want to ensure the correct ruby is used to instantiate the
refresh-mcollective-metadata script but we can accomplish this by
templatizing the shebang line rather than relying on environment
variables in the crontab.
Closes #207
> Remove environment parameter from cron resource

- README.md
Removing docs of below variables:
- $activemq_confdir
- $activemq_template
-  $activemq_memoryUsage
-  $activemq_storeUsage
-  $activemq_tempUsage
-  $activemq_console
-  $activemq_config
-  $activemq_confdir
-  $rabbitmq_confdir
-  $delete_guest_user
> MODULES-1316 - Initial commit to remove docs of variables removed from 9be4fed

- manifests/common/config.pp
- spec/classes/mcollective_spec.rb
Currently we're not setting a mode in `$site_libdi`r which basically means
we get whatever Puppet decides it should be.
On our systems this suddenly turned `$site_libdir` to '0770' meaning users
could not longer read/load/initialise plugins that were installed.
By explicitly setting it to '0644' we get the desired behaviour,
everyone can walk the path and read the files but only root can update
them.
> common/config: Set mode on site_libdir.

- manifests/common/setting.pp
- spec/defines/mcollective__common__setting_spec.rb
mcollective::common::setting was intended to follow the same pattern as
mcollective::client::setting and mcollective::server::setting, but it was
overlooked when initially written.
This patch enables this pattern as was originally intended:
mcollective::common::setting { 'daemonize':
value => 1,
}
mcollective::common::setting { 'override daemonize':
setting => 'daemonize',
value => 0,
order => 90,
}
> Allow mcollective::common::setting to be overridden

- manifests/server/config/factsource/yaml.pp
- spec/classes/mcollective_spec.rb
facter3 generates yaml facts itself - we should use that functionality.
This supercedes https://github.com/puppet-community/puppet-mcollective/pull/225
Tested with `puppet-agent-1.2.2-1.el7.x86_64`
> Fix facts with facter3

- manifests/common/config/connector/activemq.pp
- manifests/common/config/connector/rabbitmq.pp
- manifests/init.pp
- spec/classes/mcollective_spec.rb
Since the stomp connector was complaining about heartbeat not being set, I decided to expand the module to include a default heartbeat_interval of 30 secs, that can be overridden in the class declaration.
> Adding relevant heartbeat config to common settings

- manifests/server/config/factsource/yaml.pp
This fixes an issue we can have when we launch puppet agent from terminal : the current PATH may be different depending on the environment.
> hardcode PATH instead of using fact $::path

- README.md
- manifests/server/config/factsource/yaml.pp
There is concern that cron jobs run with a reduced PATH, so we still want to invoke this script with at least as full a path as the Puppet service has itself. While we want to avoid the environment parameter to set it as that is global, we can prefix the command itself in the cron job with the value of the PATH environment variable to use.
> Add back in a PATH specifier to the cron job

- README.md
- manifests/init.pp
In commit d7290fc14b the facts generation of
mcollective::server::config::factsource::yaml was changed from a template
evaluation to a external script.  This external script doesn't make use of the
mcollective::excluded_facts parameter, so stop documenting and accepting it.
> Remove the ignored excluded_facts option

- manifests/server/config/factsource/yaml.pp
When the cron job was changed to a shell invocation with -c, the closing
single-quote around the main command was omitted. This commit fixes
that omission.
> Fix missing close-quote

- README.md
- examples/README.md
fix some inaccuracies, and change mention of pupppetlabs, where we mean
puppet community.
> docs(chore): light editing of READMEs

- manifests/common/config.pp
- manifests/init.pp
This is same as following pull request.
Added identity parameter so that hosts would export fqdn as identity.
https://github.com/puppet-community/puppet-mcollective/pull/142
I have cleaned the repo and created a new pull request. Following is the issue,
While using Mcollective with Foreman, if hosts are not exporting fqdn to mcollective, 'puppet run' from foreman would not work, as foreman-proxy uses fqdn for 'mco puppet runonce ' command .
Socket.gethostname is used for finding identity by default and could give just hostname in configurations like following..
~~~
[root@centos ~]# cat /etc/sysconfig/network
NETWORKING=yes
HOSTNAME=centos
DOMAINNAME=ppp.com
1.9.3-p484 :002 > Socket.gethostname
=> "centos"
~~~
Facter is more reliable..
~~~
centos.ppp.com
~~~
Hello @hunner ,
As per the …
> Added identity parameter so that hosts would export fqdn as identity

- manifests/server/config/factsource/yaml.pp
$mcollective::excluded_facts has been remove by https://github.com/puppet-community/puppet-mcollective/commit/512630dfc8b3f979743c1a463b4e8f610299ed20 thus this line fails when using `strict_variables`.
> $mcollective::excluded_facts does not exist anymore

- manifests/defaults.pp
- manifests/init.pp
As explained in the following bugzilla, it would be ideal for Ubuntu servers to have daemonize =0.
https://tickets.puppetlabs.com/browse/MCO-167
> Disabling daemonize in Ubuntu servers

- .gitignore
Rather than specifying each module individually, which is silly
> Ignore all modules in fixtures

- manifests/init.pp
- manifests/server/config/rpcauthprovider/action_policy.pp
- spec/classes/mcollective_spec.rb
It's currently defaulting to 1, which means it's insecure by default.
I've set it to 1 by default, but at least now it can be overriden.
Tests included
> Adding options for the rpc audit provider

- manifests/init.pp
- manifests/server/config/securityprovider/ssl.pp
- spec/classes/mcollective_spec.rb
Reverts puppet-community/puppet-mcollective#244
This breaks the currently documented handling of these features. The parameters are used as the source of the content of the files, not the filenames. Please revert to original behavior.
> Revert "Fix ssl settings"

- manifests/server/config/factsource/yaml.pp
- spec/classes/mcollective_spec.rb
Fix regression caused by
https://github.com/puppet-community/puppet-mcollective/commit/8a94a8ad0705a831c97f68b344be7495e2b3d6e2
$ruby_shebang_path was ending up being either true or false, not the
string expected.
Fixed by changing to a simple if/else.
I *think* that the selector code should have worked in puppet 4 (but
didn't - maybe a puppet bug??).
According to the docs, it would never have worked in puppet 3 as
'Control variables in selectors must be variables or functions that
return values. You cannot use expressions as control variables.'
https://docs.puppetlabs.com/puppet/3.8/reference/lang_conditional.html#selectors
> Fix broken refresh-mcollective-metadata

- README.md
- manifests/defaults.pp
- manifests/server/config.pp
- spec/classes/mcollective_spec.rb
Fixes #238
Backwards compatible change that allows server_daemonize to be given as
a proper boolean.
Also fixed slight issue with
https://github.com/puppet-community/puppet-mcollective/pull/230
> Make server_daemonize a boolean

- .fixtures.yml
- manifests/server/config/factsource/yaml.pp
- metadata.json
- spec/classes/mcollective_spec.rb
Sort of surprised the spec tests didn't already pix this up.  What's the
point of puppetlabs-spec-helper STRINGIFY_FACTS option otherwise??
Anyway...
Fixed following solution from
https://docs.puppetlabs.com/puppet/latest/reference/lang_facts_and_builtin_vars.html#handling-boolean-facts-in-older-puppet-versions
> Fix ruby_shebang_path broken when fact stringified

- manifests/init.pp
- manifests/server/config.pp
The path for the certs in this module is $confdir/ssl. In the old style
mcollective packages, this directory is created at installation. However in
the new AIO puppet-agent package, this directory is not present, therefore
this module will fail to run successfully.
This commit ensures the directory exists.
> Manage ssl directory for mcollective certs

- spec/classes/mcollective_spec.rb
* Mock puppetversion and facterversion fact based on real versions
* This means the logic around changing locations depending on which version of Puppet you are on is actually tested now as part of the travis matrix
* Refactored some repeating tests into shared_examples
* Broke longer fact mocks onto new lines to make diffs better
Closes #266
> Refactors tests to test Puppet > 4 logic

- metadata.json
As part of our setup we are using librarian-puppet which is causing dependency issues with puppet-mcollective because of `richardc/puppet-datacat` version. I ran the tests and apparently there is nothing broken, also there are no major changes in datacat that could break this module.
> Bump datacat version to use < 1.0

- lib/facter/mco_version.rb
- manifests/common/config.pp
- manifests/defaults.pp
- spec/classes/mcollective_spec.rb
This PR should address an issue brought up on #puppet-community IRC
```
"warn 2015/12/10 11:06:52: config.rb:148:in `block in loadconfig' Cannot find libdir: /usr/share/mcollective/plugins"
```
Needs testing!
> Core_libdir does not exist in mcollective 2.8 and later

- spec/classes/mcollective_spec.rb
I noticed this [here](https://travis-ci.org/voxpupuli/puppet-mcollective/jobs/106630279):
`spec/classes/mcollective_spec.rb:297:1: C: Extra empty line detected at block body beginning.`
> fix rubocop complaint

- README.md
- manifests/client/install.pp
- manifests/common/config/connector/activemq/hosts_iteration.pp
- manifests/common/config/connector/rabbitmq/hosts_iteration.pp
- manifests/defaults.pp
- manifests/init.pp
- manifests/server/config/factsource/yaml.pp
- spec/classes/mcollective_spec.rb
- spec/defines/mcollective__user_spec.rb
commit 94a1facf317066cfe266412ebc7cc2a803375526
Author: Sebastian Reitenbach <sebastia@l00-bugdead-prods.de>
Date:   Tue Jun 9 20:01:17 2015 +0200
The ruby interpreter is /usr/local/bin/ruby21, named after
the ruby version it's used to run. I made the interpreter configurable
instead of hardcoding another one in.
Therefore added a ruby_interpreter parameter, that defaults to
what was there hardcoded.
SPEC tests added for the interpreter.
commit 91d0f2e9aa0e09f382d96aa18c69631fefdb2aef
Author: Sebastian Reitenbach <sebastia@l00-bugdead-prods.de>
Date:   Tue Jun 9 20:00:31 2015 +0200
* there is no distinction between client and server package,
it's just a single package. For that reason, a check is added
around client and server package definition, checking if it
might already be defined. …
> Add support for OpenBSD

- .fixtures.yml
- metadata.json
As discussed in https://github.com/voxpupuli/puppet-mcollective/pull/288 the dependency on puppetlabs-concat is not necessary anymore.
=> Remove it.
> Remove unneeded puppetlabs-concat dependency

- spec/classes/mcollective_spec.rb
* Was causing issues with transient failures in Travis (possibly because Travis machines don't have distinct enough FQDN)
> Re-add FQDN stubbing for more randomness

- manifests/server/config/factsource/yaml.pp
Previously this worked this way. I didn't track down where it changed, but I think that factsource should be set regardless (especially?) if $yaml_fact_cron is false. We generate our own fact file because we also have some variables (not actual facts) we want in there.
This gets us back into a working state, and I think it's how people that don't use the cron would prefer it?
> Use factsource and plugin.yaml regardless of $yaml_fact_cron.

- CHANGELOG.md
it's what we use in voxpupuli/release to check if something is actually
a release - because it's easier to grep for `/^#.+[rR]eleas.+#{version}/`
Also, renaming puppet-community to voxpupuli in an older release ;)
> Markdown: use ## for headers

- manifests/user.pp
use _securityprovider, otherwise files and settings won't be set if inherited from mcollective::securityprovider
> fix _securityprovider call in user.pp

- manifests/defaults.pp
When `strict_variables` is on and mcollective has yet to be installed, `mco_version` isn't defined, so referring to it here breaks compilation. The fix here uses a pattern used by puppetlabs-apt.
Seeing as this is a very minor fix and testing Puppet modules is an art I'm totally unfamiliar with, I haven't changed any tests as part of this commit. I hope that's not too much of a problem.
> Avoid compilation failure with strict_variables=true

- examples/ssl_example/mco_profile/manifests/middleware/activemq.pp
- manifests/actionpolicy/rule.pp
- manifests/client.pp
- manifests/common.pp
- manifests/server.pp
> replace validate_string with datatype

- manifests/server/config/factsource/yaml.pp
`facter -p` is officially deprecated and `puppet facts` actually returns more keys (including obsolete mapped keys, such as `operatingsystem` and `osfamily`).
> Use puppet facts instead of facter -p

- manifests/server/config/factsource/yaml.pp
`puppet facts --render-as yaml` returns a yaml file which is the
serialized version of the object:Puppet::Node::Facts.
Mcollective parses this yaml and tries to make a hash out of it.
We get an error:
```ERROR -- : yaml_facts.rb:31:in `rescue in block in
load_facts_from_source' Failed to load yaml facts from
/etc/puppetlabs/mcollective/facts.yaml: TypeError: no implicit
conversion of Puppet::Node::Facts into HasH```
So we are remove that class information out of the yaml to be able to
serialize it as a ruby hash.
> Remove Yaml class serialization information

- files/plugins/connector/redis/mcollective/connector/redis.ddl
- files/plugins/connector/redis/mcollective/connector/redis.rb
* add ddl from R.I.Pienaar for redis
* remove duplicated parameter from connector
> fix redis implementation

- manifests/client/config.pp
I've parameterised the client config, now it's possible to choose the ownership & permissions of the config file.
> Parameterize the client config

- manifests/server/config/factsource/yaml.pp
Using '%' as delimiter for the sed at the 'puppet facts' cronjob ends up
to the following error:
Subject: Cron <root@server> puppet facts --render-as yaml |sed 's
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
Replacing the delimiter with '#' instead works fine
> use different delimiter for the sed at the puppet facts cronjob

- manifests/common/config/connector/activemq/hosts_iteration.pp
- spec/classes/mcollective_spec.rb
Use
$::mcollective::middleware_ssl_cert_path
$::mcollective::middleware_ssl_key_path
instead of hard coded path for common (client)
> Make client middleware cert configurable

- manifests/common/config/connector/activemq/hosts_iteration.pp
Stops the following message from appearing on every catalog compile:
`The string '1' was automatically coerced to the numerical value 1`
Not sure if/how to test this as there's no functional change; it just stops the above appearing in the logs on the Puppetmaster.
n/a
> Quieten coerce warning

- manifests/client/config.pp
- manifests/server/config.pp
For security reason. Currently, when changes are made, puppet stores in reports and logs mcollective passwords and private keys.
> Add show_diff set to false for files storing passwords or private keys
